import { ICardRequest } from '@/types/cardManagement.type'

export const requestData: ICardRequest[] = [
  {
    request_date: '2024-05-01T18:00:00Z',
    request_id: 'REQ1',
    customer_id: 'CUST1',
    receiver_name: 'Receiver 1',
    phone: '1234567890',
    address: 'Address 1',
    postal_code: 'Postal1',
    ship_by: 'ShipBy1',
    ship_tracking: 'Tracking1',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-02T18:00:00Z',
    request_id: 'REQ2',
    customer_id: 'CUST2',
    receiver_name: 'Receiver 2',
    phone: '1234567891',
    address: 'Address 2',
    postal_code: 'Postal2',
    ship_by: 'ShipBy2',
    ship_tracking: 'Tracking2',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-03T18:00:00Z',
    request_id: 'REQ3',
    customer_id: 'CUST3',
    receiver_name: 'Receiver 3',
    phone: '1234567892',
    address: 'Address 3',
    postal_code: 'Postal3',
    ship_by: 'ShipBy3',
    ship_tracking: 'Tracking3',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-04T18:00:00Z',
    request_id: 'REQ4',
    customer_id: 'CUST4',
    receiver_name: 'Receiver 4',
    phone: '1234567893',
    address: 'Address 4',
    postal_code: 'Postal4',
    ship_by: 'ShipBy4',
    ship_tracking: 'Tracking4',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-05T18:00:00Z',
    request_id: 'REQ5',
    customer_id: 'CUST5',
    receiver_name: 'Receiver 5',
    phone: '1234567894',
    address: 'Address 5',
    postal_code: 'Postal5',
    ship_by: 'ShipBy5',
    ship_tracking: 'Tracking5',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-06T18:00:00Z',
    request_id: 'REQ6',
    customer_id: 'CUST6',
    receiver_name: 'Receiver 6',
    phone: '1234567895',
    address: 'Address 6',
    postal_code: 'Postal6',
    ship_by: 'ShipBy6',
    ship_tracking: 'Tracking6',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-07T18:00:00Z',
    request_id: 'REQ7',
    customer_id: 'CUST7',
    receiver_name: 'Receiver 7',
    phone: '1234567896',
    address: 'Address 7',
    postal_code: 'Postal7',
    ship_by: 'ShipBy7',
    ship_tracking: 'Tracking7',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-08T18:00:00Z',
    request_id: 'REQ8',
    customer_id: 'CUST8',
    receiver_name: 'Receiver 8',
    phone: '1234567897',
    address: 'Address 8',
    postal_code: 'Postal8',
    ship_by: 'ShipBy8',
    ship_tracking: 'Tracking8',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-09T18:00:00Z',
    request_id: 'REQ9',
    customer_id: 'CUST9',
    receiver_name: 'Receiver 9',
    phone: '1234567898',
    address: 'Address 9',
    postal_code: 'Postal9',
    ship_by: 'ShipBy9',
    ship_tracking: 'Tracking9',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-10T18:00:00Z',
    request_id: 'REQ10',
    customer_id: 'CUST10',
    receiver_name: 'Receiver 10',
    phone: '1234567899',
    address: 'Address 10',
    postal_code: 'Postal10',
    ship_by: 'ShipBy10',
    ship_tracking: 'Tracking10',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-11T18:00:00Z',
    request_id: 'REQ11',
    customer_id: 'CUST11',
    receiver_name: 'Receiver 11',
    phone: '1234567810',
    address: 'Address 11',
    postal_code: 'Postal11',
    ship_by: 'ShipBy11',
    ship_tracking: 'Tracking11',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-12T18:00:00Z',
    request_id: 'REQ12',
    customer_id: 'CUST12',
    receiver_name: 'Receiver 12',
    phone: '1234567811',
    address: 'Address 12',
    postal_code: 'Postal12',
    ship_by: 'ShipBy12',
    ship_tracking: 'Tracking12',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-13T18:00:00Z',
    request_id: 'REQ13',
    customer_id: 'CUST13',
    receiver_name: 'Receiver 13',
    phone: '1234567812',
    address: 'Address 13',
    postal_code: 'Postal13',
    ship_by: 'ShipBy13',
    ship_tracking: 'Tracking13',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-14T18:00:00Z',
    request_id: 'REQ14',
    customer_id: 'CUST14',
    receiver_name: 'Receiver 14',
    phone: '1234567813',
    address: 'Address 14',
    postal_code: 'Postal14',
    ship_by: 'ShipBy14',
    ship_tracking: 'Tracking14',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-15T18:00:00Z',
    request_id: 'REQ15',
    customer_id: 'CUST15',
    receiver_name: 'Receiver 15',
    phone: '1234567814',
    address: 'Address 15',
    postal_code: 'Postal15',
    ship_by: 'ShipBy15',
    ship_tracking: 'Tracking15',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-16T18:00:00Z',
    request_id: 'REQ16',
    customer_id: 'CUST16',
    receiver_name: 'Receiver 16',
    phone: '1234567815',
    address: 'Address 16',
    postal_code: 'Postal16',
    ship_by: 'ShipBy16',
    ship_tracking: 'Tracking16',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-17T18:00:00Z',
    request_id: 'REQ17',
    customer_id: 'CUST17',
    receiver_name: 'Receiver 17',
    phone: '1234567816',
    address: 'Address 17',
    postal_code: 'Postal17',
    ship_by: 'ShipBy17',
    ship_tracking: 'Tracking17',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-18T18:00:00Z',
    request_id: 'REQ18',
    customer_id: 'CUST18',
    receiver_name: 'Receiver 18',
    phone: '1234567817',
    address: 'Address 18',
    postal_code: 'Postal18',
    ship_by: 'ShipBy18',
    ship_tracking: 'Tracking18',
    status: 'shipped',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
  {
    request_date: '2024-05-19T18:00:00Z',
    request_id: 'REQ19',
    customer_id: 'CUST19',
    receiver_name: 'Receiver 19',
    phone: '1234567818',
    address: 'Address 19',
    postal_code: 'Postal19',
    ship_by: 'ShipBy19',
    ship_tracking: 'Tracking19',
    status: 'pending',
    note: 'Khuyến cáo: các thao tác với kí tự nằm ngoài string, sẽ không có ảnh hưởng tới string hay các thuộc tính của string',
  },
]
